version: '2'
services:
  django-redis:
    build: .
    volumes:
     - ./:/django-redis-sentinel
    depends_on:
    - redis-master
    - redis-slave1
    - redis-slave2
    - sentinel1
    - sentinel2
    - sentinel3
    ports:
     - "2005:22"

  sentinel1:
    build: sentinel
    environment:
    - SENTINEL_DOWN_AFTER=5000
    - SENTINEL_FAILOVER=180000
    depends_on:
    - redis-master
    - redis-slave1
    - redis-slave2

  sentinel2:
    build: sentinel
    environment:
    - SENTINEL_DOWN_AFTER=5000
    - SENTINEL_FAILOVER=180000
    depends_on:
    - redis-master
    - redis-slave1
    - redis-slave2

  sentinel3:
    build: sentinel
    environment:
    - SENTINEL_DOWN_AFTER=5000
    - SENTINEL_FAILOVER=180000
    depends_on:
    - redis-master
    - redis-slave1
    - redis-slave2

  redis-master:
    image: redis:4-alpine

  redis-slave1:
    image: redis:4-alpine
    command: redis-server --slaveof redis-master 6379
    depends_on:
    - redis-master

  redis-slave2:
    image: redis:4-alpine
    command: redis-server --slaveof redis-master 6379
    depends_on:
    - redis-master
